apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - args:
    - -f
    - /dev/null
    command:
    - tail
    image: docker-hub-remote.artifactory.teslamotors.com/nicolaka/netshoot
    name: main
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "200Mi"
