apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: grafana-enterprise
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: latest
    argocd.argoproj.io/instance: grafana-enterprise
    helm.sh/chart: grafana-7.3.3
  name: grafana-enterprise
  namespace: grafana-enterprise
spec:
  rules:
    - host: monitoring.tesla.cn
      http:
        paths:
          - backend:
              service:
                name: grafana-enterprise
                port:
                  number: 80
            path: /
            pathType: Prefix

