apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.3.3
    argocd.argoproj.io/instance: grafana
    helm.sh/chart: grafana-6.49.0
  name: grafana
  namespace: platform-engineering-resources
spec:
  rules:
  - host: grafana.cn-pvg16-prd-r1-mon.k8s.tesla.com
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 3000
        path: /
        pathType: Prefix
